In [1]:
import numpy as np

## 1. Data Types & Attributes

In [2]:
# Numpy's main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
                [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

 ## 2. Creating Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 2, 2, 6, 5],
       [3, 9, 1, 0, 6],
       [4, 5, 8, 3, 4]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.04750687, 0.69190811, 0.61874984],
       [0.92660149, 0.64458037, 0.26728124],
       [0.17020743, 0.21661964, 0.89936127],
       [0.32410862, 0.22170432, 0.10709839],
       [0.68829765, 0.0301448 , 0.97625023]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.85835578, 0.27444785, 0.65555049],
       [0.36859451, 0.00122622, 0.29290601],
       [0.55353747, 0.04314838, 0.92574541],
       [0.45889243, 0.02453552, 0.34388551],
       [0.54248463, 0.63307182, 0.30464271]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random(size=(5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [32]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1

array([1, 2, 3])

In [34]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1[0]

1

In [37]:
a2[0]

array([1. , 2. , 3.3])

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2[1]

array([4. , 5. , 6.5])

In [40]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [41]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [42]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [43]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating and Comparing Arrays

### Arithmetic

In [44]:
a1

array([1, 2, 3])

In [45]:
ones = np.ones(3)

In [46]:
ones

array([1., 1., 1.])

In [47]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1 - ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [52]:
a2 * a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [53]:
a1 /ones

array([1., 2., 3.])

In [54]:
a2 / a1


array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [55]:
# Floor division removes the decimals (rounds down) 
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [56]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [57]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [58]:
np.add(a1, ones)

array([2., 3., 4.])

In [59]:
# modulo shows the remainders
a1 % 2

array([1, 0, 1])

In [60]:
a1 / 2

array([0.5, 1. , 1.5])

In [61]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [62]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [63]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Performing the same operation in a number of things

In [64]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [65]:
sum(listy_list)

6

In [66]:
sum(a1)

6

In [67]:
np.sum(a1)

6

#### Use Python's methods `sum()` on Python datatypes and use NumPy's methods `np.sum()` on NumPy arrays

In [72]:
# Create a massive numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [74]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [75]:
%timeit sum(massive_array) # Python sum
%timeit np.sum(massive_array) # NumPy sum

15.4 ms ± 484 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.6 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [76]:
 np.mean(a2)

3.6333333333333333

In [77]:
np.max(a2)

6.5

In [78]:
np.min(a2)

1.0

In [81]:
# Standard Deviation = a measure of how spread out a group of numbers is from the mean. Square root of variance
np.std(a2)

1.8226964152656422

In [83]:
# Variance =  measure of the average degree to which each number is different to the mean.
# Higher variance =  wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [86]:
# Standard deviation = Squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422