In [2]:
import numpy as np

## 1. Data Types & Attributes

In [3]:
# Numpy's main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
                [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(3, 2, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

 ## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 2, 4, 0, 7],
       [2, 3, 5, 7, 8],
       [8, 6, 7, 7, 1]])

In [30]:
random_array.size

15

In [31]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.40909082, 0.01570934, 0.06432399],
       [0.03893075, 0.87490513, 0.06355727],
       [0.77899097, 0.9067676 , 0.04793039],
       [0.53855715, 0.35538   , 0.58914874],
       [0.49389383, 0.15902609, 0.46270498]])

In [35]:
random_array_2.shape

(5, 3)

In [36]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.89290042, 0.75593945, 0.0953776 ],
       [0.79537731, 0.41339588, 0.15524249],
       [0.54431998, 0.53813219, 0.41410726],
       [0.23397386, 0.73311193, 0.85244805],
       [0.4630946 , 0.20188715, 0.81355851]])

In [37]:
# Pseudo-random numbers
np.random.seed()